In [3]:
my_list = range(2,6)

In [4]:
print(my_list)

range(2, 6)


In [5]:
range?

In [12]:
my_list = ['a','b','c']
my_indexes = range(0,3)


In [13]:
for i in my_indexes:
    print(my_list[i])

a
b
c


In [16]:
import os

In [18]:
os.listdir()

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'images',
 'intro.ipynb',
 'loop.ipynb',
 'plotting',
 'README.md']

In [19]:
import numpy

In [20]:
import numpy as np

In [22]:
my_list = [1,2,3,4,5]

In [24]:
np.median(my_list)

3.0

In [25]:
my_array = np.array( [1,2,3,4,5] )

In [27]:
my_array + 1

array([2, 3, 4, 5, 6])

In [29]:
type(my_list)

list

In [30]:
my_list+1

TypeError: can only concatenate list (not "int") to list

In [31]:
my_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

In [36]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
my_matrix

['1,2,3', '4,5,6', '7,8,9']

In [37]:
type(my_matrix)

numpy.ndarray

In [38]:
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
np.mean?

<function float.hex>