In [6]:
list1 = [1,2,3]
list2 = ['hello', 'world', ['a','b','c']]

print( list1 + list2 )

[1, 2, 3, 'hello', 'world', ['a', 'b', 'c']]


In [5]:
list1 = list1 + ['last']

print( list1 )

list[0]

[1, 2, 3, 'last', 'last', 'last']


In [12]:
my_dict = { 'a':1, 'b':2, 3:'c' }

my_dict[3]

'c'

In [13]:
my_list = [ ['a',1], ['b',2] ]

In [17]:
my_tuple = (1,2,3,4,'hello')

print(my_tuple)

(1, 2, 3, 4, 'hello')


In [21]:
my_list = ['a','b','c','d']

for i, letter in enumerate(my_list):
    print(i, letter)

0 a
1 b
2 c
3 d


In [22]:
x = 5

if x > 5:
    print('bigger than 5')
elif x < 5:
    print('smaller than 5')
else:
    print('must be 5')

must be 5


In [ ]:
import numpy as np

In [41]:
my_list = [1,2,3,4,5]

In [39]:
np.mean(my_list)

In [45]:
my_array = np.array( [1,2,3,4,5] )

In [49]:
x = 1
b = 2
my_array

array([1, 2, 3, 4, 5])

In [50]:
my_array

array([1, 2, 3, 4, 5])

In [52]:
my_array.T

array([1, 2, 3, 4, 5])

In [70]:
my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [71]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
my_matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [73]:
my_array.reshape([-1, 1])

array([[  4.94065646e-324],
       [  9.88131292e-324],
       [  1.48219694e-323],
       [  1.97626258e-323],
       [  2.47032823e-323]])

In [74]:
my_array.dtype

dtype('float64')

In [75]:
type(my_array)

numpy.ndarray

In [69]:
my_array.dtype # attribute
my_array.transpose() # function

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323,
         1.97626258e-323,   2.47032823e-323])

In [67]:
my_array.astype(float)

array([  4.94065646e-324,   9.88131292e-324,   1.48219694e-323,
         1.97626258e-323,   2.47032823e-323])

In [68]:
my_array[0:2]

array([  4.94065646e-324,   9.88131292e-324])

In [78]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
my_matrix[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
my_matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
my_list = [i*2 for i in [5,6,7]]

In [102]:
my_list = [1,2,3,4,5,6,7,8]

my_even_nums = []

for number in my_list:
    if number % 2 == 0:
        my_even_nums.append(number)

In [103]:
my_even_nums

[2, 4, 6, 8]

In [107]:
my_even_nums = [i for i in my_list if i%2==0] # list comprehension

In [108]:
my_even_nums

[2, 4, 6, 8]

In [85]:
np.mean(my_matrix, axis=0)

array([ 4.,  5.,  6.])

In [95]:
pi = np.pi

In [97]:
type(pi)

float

In [98]:
pi?

In [100]:
x = 2.3
